<a href="https://colab.research.google.com/github/Ahmamaher/Accident-Data-Analysis/blob/main/Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Project Data - accident data**

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# **Data Gathering**

In [54]:
df = pd.read_csv('/content/accident data.csv')
df

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200701BS64157,Serious,05-06-2019,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
1,200701BS65737,Serious,02-07-2019,51.495029,Daylight,Kensington and Chelsea,-0.173647,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,200701BS66127,Serious,26-08-2019,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,NaN,Urban,NaN,Taxi/Private hire car
3,200701BS66128,Serious,16-08-2019,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,200701BS66837,Slight,03-09-2019,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,NaN,Urban,NaN,Other vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119968,200743P083087,Slight,05-08-2019,51.901939,Daylight,West Oxfordshire,-1.627008,1,2,Dry,Single carriageway,Rural,Fine no high winds,Motorcycle over 500cc
119969,200743P083097,Slight,11-09-2019,51.752584,Daylight,Oxford,-1.248684,1,2,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
119970,200743P083107,Serious,07-10-2019,51.947066,Daylight,Cherwell,-1.207610,1,2,Dry,Roundabout,Rural,Fine no high winds,Van / Goods 3.5 tonnes mgw or under
119971,200743P083117,Fatal,11-11-2019,51.815171,Darkness - no lighting,West Oxfordshire,-1.425354,1,2,Dry,Single carriageway,Rural,Fine no high winds,Motorcycle 125cc and under
119972,200743P084037,Slight,07-03-2019,51.780572,Daylight,West Oxfordshire,-1.375783,1,5,Dry,Single carriageway,Rural,Fine no high winds,Goods 7

# Data **Assessing**

In [49]:
df.head()

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200701BS64157,Serious,05-06-2019,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1.0,2.0,Dry,Single carriageway,Urban,Fine no high winds,Car
1,200701BS65737,Serious,02-07-2019,51.495029,Daylight,Kensington and Chelsea,-0.173647,1.0,2.0,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,200701BS66127,Serious,26-08-2019,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1.0,3.0,Dry,NaN,Urban,NaN,Taxi/Private hire car
3,200701BS66128,Serious,16-08-2019,51.495478,Daylight,Kensington and Chelsea,-0.202731,1.0,4.0,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,200701BS66837,Slight,03-09-2019,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1.0,2.0,Dry,NaN,Urban,NaN,Other vehicle

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29856 entries, 0 to 29855
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Index                    29856 non-null  object
 1   Accident_Severity        29856 non-null  object
 2   Accident Date            29856 non-null  object
 3   Latitude                 29856 non-null  float64
 4   Light_Conditions         29856 non-null  object
 5   District Area            29856 non-null  object
 6   Longitude                29855 non-null  float64
 7   Number_of_Casualties     29855 non-null  float64
 8   Number_of_Vehicles       29855 non-null  float64
 9   Road_Surface_Conditions  29846 non-null  object
 10  Road_Type                29527 non-null  object
 11  Urban_or_Rural_Area      29855 non-null  object
 12  Weather_Conditions       29233 non-null  object
 13  Vehicle_Type             29855 non-null  object
dtypes: float64(4), object(10)
memory usage: 3.2+ MB

In [ ]:
df.isnull().sum()

Index                         0
Accident_Severity             0
Accident Date                 0
Latitude                      0
Light_Conditions              0
District Area                 0
Longitude                     0
Number_of_Casualties          1
Number_of_Vehicles            1
Road_Surface_Conditions      23
Road_Type                   813
Urban_or_Rural_Area           1
Weather_Conditions         1237
Vehicle_Type                  1
dtype: int64

In [ ]:
df.describe()

           Latitude     Longitude  Number_of_Casualties  Number_of_Vehicles
count  45043.000000  45042.000000          45042.000000        45042.000000
mean      52.522216     -1.315077              1.323209            1.828715
std        1.076250      1.259413              0.807520            0.676769
min       51.292694     -3.599412              1.000000            1.000000
25%       51.510869     -2.547715              1.000000            1.000000
50%       51.627483     -0.411304              1.000000            2.000000
75%       53.497676     -0.113606              1.000000            2.000000
max       55.049865      0.313329             40.000000           14.000000

In [ ]:
df.duplicated().sum()

0

## Quality **Issues**

**1-Error in the data type**

    1-The Index column must be an integer (int) but is an object
    2-The Accident Date column is an object instead of a datetime
2-Missing values

    1-Longityde → One row is missing
    2-Number_of_casualties and Number_of_vehicles → Missing unit queue
    3-Road_surface_condits → 10 missing values
    4-Road_type → 329 missing value
    5-Urban_or_rural_area → One row is missing
    6-Weather_Conditions → 623 missing value

# **Data Cleaning**

### Dealing with incorrect data types

**Define:**
The Index column must be an integer (int) but is an object

**Code:**

In [ ]:
df['Index'] = df['Index'].str.extract('(\d+)').astype(int)

# Test:

In [ ]:
df.dtypes

Index                        int64
Accident_Severity           object
Accident Date               object
Latitude                   float64
Light_Conditions            object
District Area               object
Longitude                  float64
Number_of_Casualties       float64
Number_of_Vehicles         float64
Road_Surface_Conditions     object
Road_Type                   object
Urban_or_Rural_Area         object
Weather_Conditions          object
Vehicle_Type                object
dtype: object

**Define:**
2-The Accident Date column is an object instead of a datetime

**Code**:

In [ ]:
df['Accident Date'] = pd.to_datetime(df['Accident Date'], format='%d-%m-%Y')

**Test:**

In [ ]:
df.dtypes

Index                               int64
Accident_Severity                  object
Accident Date              datetime64[ns]
Latitude                          float64
Light_Conditions                   object
District Area                      object
Longitude                         float64
Number_of_Casualties              float64
Number_of_Vehicles                float64
Road_Surface_Conditions            object
Road_Type                          object
Urban_or_Rural_Area                object
Weather_Conditions                 object
Vehicle_Type                       object
dtype: object

**define:** Number_of_Casualties and number_of_vehicles their type Float64 but they are correct numbers

In [ ]:
df['Number_of_Casualties'] = df['Number_of_Casualties'].astype(int)
df['Number_of_Vehicles'] = df['Number_of_Vehicles'].astype(int)

### **Missing values**

**Define:**
1-Fill out the lost values ​​with the most common values ​​(Mode) of the classified columns

2-Fill in the lost values ​​in the arithmetic middle of the digital columns


**Code:**

In [ ]:
df['Road_Surface_Conditions'].fillna(df['Road_Surface_Conditions'].mode()[0], inplace=True)
df['Road_Type'].fillna(df['Road_Type'].mode()[0], inplace=True)
df['Weather_Conditions'].fillna(df['Weather_Conditions'].mode()[0], inplace=True)

<ipython-input-16-53a52566a8e3>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Road_Surface_Conditions'].fillna(df['Road_Surface_Conditions'].mode()[0], inplace=True)
<ipython-input-16-53a52566a8e3>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Road_Type'].fillna(df['Road_Type'].mode()[0], inplace=True)
<ipython-input-16-53a52566a8e3>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weather_Conditions'].fillna(df['Weather_Conditions'].mode()[0], inplace=True)

**Code**:

In [ ]:
df['Number_of_Casualties'].fillna(df['Number_of_Casualties'].mean(), inplace=True)
df['Number_of_Vehicles'].fillna(df['Number_of_Vehicles'].mean(), inplace=True)

<ipython-input-15-09b98810cc44>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Number_of_Vehicles'].fillna(df['Number_of_Vehicles'].mean(), inplace=True)

**Test:**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45043 entries, 0 to 45042
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Index                    45043 non-null  int64
 1   Accident_Severity        45043 non-null  object
 2   Accident Date            45043 non-null  datetime64[ns]
 3   Latitude                 45043 non-null  float64
 4   Light_Conditions         45043 non-null  object
 5   District Area            45042 non-null  object
 6   Longitude                45042 non-null  float64
 7   Number_of_Casualties     45043 non-null  int64
 8   Number_of_Vehicles       45043 non-null  int64
 9   Road_Surface_Conditions  45043 non-null  object
 10  Road_Type                45043 non-null  object
 11  Urban_or_Rural_Area      45042 non-null  object
 12  Weather_Conditions       45043 non-null  object
 13  Vehicle_Type             45042 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(3), object(8)
memory usage: 4.8+ MB

# **Data Storing**

In [ ]:
df.to_csv('cleaned_data.csv', index=False)

In [ ]:
from google.colab import files
files.download('cleaned_data.csv')